### ISSUE TITLE
Add a warning about potentially incorrect schedules in future dates

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#147]
**Feature Request**
- **Brief summary** (What you want): Until a backend is built, I think it might be good to place a warning about future dates and schedules being potentially incorrect when users use the "see ahead" feature on the Bell Schedule tab.
- **Longer description** (more details about your request): See above. Perhaps for implementation, store a variable that stores the last date of when the calendar schedules are updated until, and if a user views ahead of that date display a warning.
- **Resources** (links,screenshots,theoretical design/mockups.): N/A

**Comment by RyantheKing** [comment]
Well we made it so its impossible to see dates in other years.  And Bryan put in all the schedules correctly for this year.

**Comment by SuperPEKKA336** [comment]
I got this one.

**Comment by awesomehaze** [comment]
> I got this one.

Let me know if you want me to reopen this
