### ISSUE TITLE
Create a logo for PWA

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#19]

**Comment by RyantheKing** [comment]
![LOGO](https://user-images.githubusercontent.com/48844450/54857256-85450880-4cbb-11e9-8b03-a904a2646b72.png)

**Comment by RyantheKing** [comment]
Real one
![LOGO (1)](https://user-images.githubusercontent.com/48844450/54858165-66954080-4cc0-11e9-8a89-1eb43856a9b3.png)
