### ISSUE TITLE
Implement missing schedules

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#2]
Here are all of the schedules the app has implemented in [src/schedule/schedules.ts](https://github.com/lchsiteam/lchs-go-pwa/blob/master/src/schedule/schedules.ts):

- [x] Regular Schedule 9-12
- [x] Block Schedule (odd) 9-12
- [x] Block Schedule (even) 9-12
- [x] Assembly Schedule 9-12
- [x] Minimum Day 9-12

There's also 7/8 schedules. To prevent needless duplication, we could merge both their schedules into one variable and specify which periods are for all grades, 9-12, and 7/8:

- [x] Regular Schedule 7/8
- [x] Block Schedule (odd) 7/8
- [x] Block Schedule (even) 7/8
- [x] Assembly Schedule 7/8
- [x] Minimum Day 7/8

And there's also finals:
- [x] Finals Schedule ????????

Refer to https://www.lchsspartans.net/apps/bell_schedules/

**Comment by the-non-feline** [comment]
mission accomplished?
