### ISSUE TITLE
Add Remaining Time to Tab Title

### ISSUE THREAD

**Issue by awesomehaze** [lchsiteam/lchs-go-pwa#293]
**Feature Request**
- **Brief summary** (What you want): Make it say something like "LCHS Go, 20 minutes" in the tab title, so we don't need the extension to get that quick glance goodness.

**Comment by EnderLord0042** [comment]
Ooh, that's a good idea! It would probably be pretty easy to implement too! Wherever we have code that edits the HTML element for the clock, we could also just edit the title element.

**Comment by awesomehaze** [comment]
#294
