### ISSUE TITLE
Assembly Schedule Incorrect

### ISSUE THREAD

**Issue by Apricitine** [lchsiteam/lchs-go-pwa#355]
**Bug Report**
- **Brief summary** (what happened): Lunch schedule occurs before period 4 begins, outdated schedule
- **Fix**: In lchs-go-pwa/src/schedule/schedules.ts, and WeirdAssemblySchedule78, edit LUNCH to fix. Could also `switch case` to change schedule based on date
- EDIT High school schedule also incorrect in this particular case

**Comment by awesomehaze** [comment]
Thanks for letting us know, we unfortunately had the schedule incorrect. We didn't realize that they changed the assembly schedule this year because we haven't had one yet.
