### ISSUE TITLE
New Issue Templates

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#36]
Do we want to move our feature suggestions system to Github? Github has a feature where you can set up issue templates that load when a user creates a new issue on our repository. Please take a look at this feature here: https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by epicodaboss** [comment]
Issue name:
Person who suggested issue:
Brief summary:
Tags:


Longer description:




Resources(links,etc.):

**Comment by epicodaboss** [comment]
**Example**

Brief summary:

Longer description(more specific, how the bug occured):

Settings(Grade level, custom settings, anything relevant):

Resources(links,screenshots.):

**Comment by epicodaboss** [comment]
**Feature Request**
- **Brief summary** (What you want):
- **Longer description** (more details about your request):
- **Resources** (links,screenshots,theoretical design/mockups.):
