### ISSUE TITLE
Rainbow Theme

### ISSUE THREAD

**Issue by RyantheKing** [lchsiteam/lchs-go-pwa#40]
Make a theme that slowly transistions between gradient themes, blue and light blue fades to green, fades to yellow, fades to red, fades to pink, fades to purple, fades back to blue etc.

**Comment by RyantheKing** [comment]
https://repl.it/@RyandaKing/swirly
I made a spinning theme, next will probably be a scrolling one, and then one that fades between colors.  Anyone feel free to help.

**Comment by the-non-feline** [comment]
you asked and you gave
