### ISSUE TITLE
Elementary Schedules

### ISSUE THREAD

**Issue by pix-code** [lchsiteam/lchs-go-pwa#437]
Should we remove support for elementary school? Or does it not matter as it is going to be unmaintained in the future. This would involve removing the schedules for elementary school and also other unused schedules.

**Comment by Apricitine** [comment]
i think removing support would be fine
its not in the new go and idk if any elementary kids even have it

**Comment by awesomehaze** [comment]
It was just an old thing and I definitely think removing is a good idea. Or we just migrate away completely.

**Comment by Apricitine** [comment]
👍

**Comment by mark-crichton** [comment]
late reply, but yep you can go ahead and remove them (don't think those were really used in old go, and new go doesn't have them as previously mentioned)

**Comment by Apricitine** [comment]
so yeah we can just leave as is bc this is deprecated
ill close
