### ISSUE TITLE
Add introduction guide to using LCHS Go

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#58]
If the app grows, we would want to direct first-time users to a simple guide to using LCHS Go.

**Comment by epicodaboss** [comment]
How to use LCHS Go
*A comprehensive guide* (Version 1.0)

Table of Contents
**Part 1:** Overview, 
**Part 2:**The Now page
**Part 3:** Custom settings

**Part 1**
**-----------------**
*Overview*
Welcome to LCHS Go, a progressive web application developed by students at LCHS. This app allows you to:

1. Know what period it currently is

2. Know the time until next period

3. Easily find a bell schedule of the current day

This app is also accompanied by an extention, which is more convenient, as it will open on the page you are currently on. The extention, however, will not allow you to customize the application.
To install the extention, click here: 
https://chrome.google.com/webstore/detail/lchs-go/cmmaleejnmjplfcnhojldkiejpndakad

This app is very intuitive. It also updates automatically, without the need to refresh.
All of the nessary information will be displayed on the "Now" page, the page that appears initally when on the website, and the page that appears when clicking on the extention.(Part 2)
All of the settings can be accessed in the "About" page.(Part 3)




**Part 2**
**---------------**
*The Now section*
When the large "Now" button is selected, smaller buttons, marked "Now" and "Bell schedule", appear initally, the "Now" button will be selected. However, by clicking, you will be brought to the bell schedule of the current day of the selected grade(See part two to change the current grade).

The Now section, which is the inital section, can be reaccessed by clicking the aforementioned smaller "Now" button. The Now section has three subsections:
1. Current Period
This section shows which period is currently happening for the selected period.
2. Period End/Until Next
This section shows how much time is remaining until the next period. By clicking this section, the text below will toggle between showing the name of the next period and how long until it, and the time remaining for the current period.
3.Current Time/Last updated
This section shows the current time. This app updates automatically, without the need to refresh, so the current time will always be that of the Pacific Time Zone(assuming the application is working).

**Part 3**
**---------------**
*The About section*
