### ISSUE TITLE
Rewrite README.md to include project information

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#6]
We need someone to update the README.md with the project information.

In the new README.md, please include:
1. A header title
2. A description of the LCHS Go Project
3. Screenshots
4. Credits
5. Steps to build project
6. Steps to contribute feedback (use email)
7. Copyright disclaimer

Once you've made a pull request containing the new README.md, please reference this issue number.

**Comment by RyantheKing** [comment]
I will do this by next Monday if Robin doesn't, but I wanted to give him the chance because I told him it would be a good no code issue for him.

**Comment by RyantheKing** [comment]
Dis as been done for a while
