### ISSUE TITLE
Preview Bell Schedules For Future Days

### ISSUE THREAD

**Issue by lciteam** [lchsiteam/lchs-go-pwa#62]

**Comment by epicodaboss** [comment]
ideas for how to do this
==================
third page on "now section" that contains a drop down menu 
ddm contains 7 day options for the next 7 days
choosing each day shows the bell schedule for that day
- jerry-rigged potential solution: change the system's clock for that user temporarily to force the system to show that user the schedule
else keep it as a seperate, updating variable that's user dependent

**Comment by epicodaboss** [comment]
hi
====

**Comment by RyantheKing** [comment]
Being replaced by calendar,
