### ISSUE TITLE
Make "until end of period" display the current period

### ISSUE THREAD

**Issue by awesomehaze** [lchsiteam/lchs-go-pwa#63]
Eg. x minutes until period x ends
x minutes until school gets out

**Comment by the-non-feline** [comment]
ikr, i never have any idea what my current period is. Pls fix this! 

![image](https://user-images.githubusercontent.com/32406395/56408490-a1d85000-6229-11e9-8413-348d22b3b8b6.png)

(:

**Comment by awesomehaze** [comment]
> ikr, i never have any idea what my current period is. Pls fix this!
> 
> ![image](https://user-images.githubusercontent.com/32406395/56408490-a1d85000-6229-11e9-8413-348d22b3b8b6.png)
> 
> (:

Same.
