### ISSUE TITLE
Add Themes to LCHS Go

### ISSUE THREAD

**Issue by encadyma** [lchsiteam/lchs-go-pwa#9]
Allow people to theme the LCHS Go page. Get some nice colors, and explore some interesting colors for a little bit! CSS and some JS knowledge necessary (LocalStorage, likely?).

If you are considering this and need some inspiration to get started, consider building a dark theme and a Spartan school color theme.

**Comment by cassiemaxine** [comment]
#f0fla0 to #e376a38c
#a8d7c9 to #769de3
#ddeb2353 to #eb232370
#f2f3aea3 to #16c2b47a
#93ef91c4 to #ae38a92e
#2512c291 to #3897ae63
#b94296ba to #bcc4e5
#62flde to #4100ffa6
#ffffff00 to #4100ff

**Comment by encadyma** [comment]
Suggestion: remove the inactive indicator
